In [1]:
import numpy as np
import tensorflow as tf

In [2]:
x = np.linspace(-2*np.pi,2*np.pi,1000).reshape(-1,1)
y = np.sin(x)

In [3]:
ann = tf.keras.models.Sequential()

In [4]:
ann.add(tf.keras.layers.Dense(units=40,activation='sigmoid'))

In [5]:
ann.add(tf.keras.layers.Dense(units=12,activation='sigmoid'))

In [6]:
ann.add(tf.keras.layers.Dense(units=1))

In [7]:
ann.compile(loss='mean_squared_error' ,optimizer='adam',metrics=['mean_squared_error'])

In [8]:
ann.fit(x,y,epochs=1000,batch_size=16)

Epoch 1/1000
63/63 [==============================] - 1s 1ms/step - loss: 0.5859 - mean_squared_error: 0.5859
Epoch 2/1000
63/63 [==============================] - 0s 929us/step - loss: 0.4467 - mean_squared_error: 0.4467
Epoch 3/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.4410 - mean_squared_error: 0.4410
Epoch 4/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.4390 - mean_squared_error: 0.4390
Epoch 5/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.4346 - mean_squared_error: 0.4346
Epoch 6/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.4343 - mean_squared_error: 0.4343
Epoch 7/1000
63/63 [==============================] - 0s 921us/step - loss: 0.4349 - mean_squared_error: 0.4349
Epoch 8/1000
63/63 [==============================] - 0s 933us/step - loss: 0.4326 - mean_squared_error: 0.4326
Epoch 9/1000
63/63 [==============================] - 0s 934us/step - loss: 0.4340 - mean_squared_error: 0.4340
Ep

63/63 [==============================] - 0s 1ms/step - loss: 0.1047 - mean_squared_error: 0.1047
Epoch 146/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.1040 - mean_squared_error: 0.1040
Epoch 147/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.1033 - mean_squared_error: 0.1033
Epoch 148/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.1028 - mean_squared_error: 0.1028
Epoch 149/1000
63/63 [==============================] - 0s 998us/step - loss: 0.1025 - mean_squared_error: 0.1025
Epoch 150/1000
63/63 [==============================] - 0s 894us/step - loss: 0.1014 - mean_squared_error: 0.1014
Epoch 151/1000
63/63 [==============================] - 0s 772us/step - loss: 0.1016 - mean_squared_error: 0.1016
Epoch 152/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.1012 - mean_squared_error: 0.1012
Epoch 153/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.1002 - mean_squared_error: 0.1002
E

Epoch 289/1000
63/63 [==============================] - 0s 756us/step - loss: 0.0711 - mean_squared_error: 0.0711
Epoch 290/1000
63/63 [==============================] - 0s 758us/step - loss: 0.0712 - mean_squared_error: 0.0712
Epoch 291/1000
63/63 [==============================] - 0s 741us/step - loss: 0.0702 - mean_squared_error: 0.0702
Epoch 292/1000
63/63 [==============================] - 0s 782us/step - loss: 0.0706 - mean_squared_error: 0.0706
Epoch 293/1000
63/63 [==============================] - 0s 741us/step - loss: 0.0700 - mean_squared_error: 0.0700
Epoch 294/1000
63/63 [==============================] - 0s 708us/step - loss: 0.0706 - mean_squared_error: 0.0706
Epoch 295/1000
63/63 [==============================] - 0s 760us/step - loss: 0.0694 - mean_squared_error: 0.0694
Epoch 296/1000
63/63 [==============================] - 0s 885us/step - loss: 0.0703 - mean_squared_error: 0.0703
Epoch 297/1000
63/63 [==============================] - 0s 644us/step - loss: 0.0695 - m

63/63 [==============================] - 0s 1ms/step - loss: 0.0489 - mean_squared_error: 0.0489
Epoch 433/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0488 - mean_squared_error: 0.0488
Epoch 434/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0485 - mean_squared_error: 0.0485
Epoch 435/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0493 - mean_squared_error: 0.0493
Epoch 436/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0486 - mean_squared_error: 0.0486
Epoch 437/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0493 - mean_squared_error: 0.0493
Epoch 438/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0478 - mean_squared_error: 0.0478
Epoch 439/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0480 - mean_squared_error: 0.0480
Epoch 440/1000
63/63 [==============================] - 0s 937us/step - loss: 0.0487 - mean_squared_error: 0.0487
Epoch

63/63 [==============================] - 0s 1ms/step - loss: 0.0320 - mean_squared_error: 0.0320
Epoch 577/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0325 - mean_squared_error: 0.0325
Epoch 578/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0316 - mean_squared_error: 0.0316
Epoch 579/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0315 - mean_squared_error: 0.0315
Epoch 580/1000
63/63 [==============================] - 0s 955us/step - loss: 0.0320 - mean_squared_error: 0.0320
Epoch 581/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0320 - mean_squared_error: 0.0320
Epoch 582/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0329 - mean_squared_error: 0.0329
Epoch 583/1000
63/63 [==============================] - 0s 830us/step - loss: 0.0319 - mean_squared_error: 0.0319
Epoch 584/1000
63/63 [==============================] - 0s 778us/step - loss: 0.0318 - mean_squared_error: 0.0318
E

Epoch 721/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0183 - mean_squared_error: 0.0183
Epoch 722/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0180 - mean_squared_error: 0.0180
Epoch 723/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0183 - mean_squared_error: 0.0183
Epoch 724/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0181 - mean_squared_error: 0.0181
Epoch 725/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0172 - mean_squared_error: 0.0172
Epoch 726/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0172 - mean_squared_error: 0.0172
Epoch 727/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0176 - mean_squared_error: 0.0176
Epoch 728/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0176 - mean_squared_error: 0.0176
Epoch 729/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0177 - mean_squared_error:

Epoch 794/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0129 - mean_squared_error: 0.0129
Epoch 795/1000
63/63 [==============================] - 0s 995us/step - loss: 0.0121 - mean_squared_error: 0.0121
Epoch 796/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0122 - mean_squared_error: 0.0122
Epoch 797/1000
63/63 [==============================] - 0s 896us/step - loss: 0.0118 - mean_squared_error: 0.0118
Epoch 798/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0117 - mean_squared_error: 0.0117
Epoch 799/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0123 - mean_squared_error: 0.0123
Epoch 800/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0113 - mean_squared_error: 0.0113
Epoch 801/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0114 - mean_squared_error: 0.0114
Epoch 802/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0114 - mean_squared_er

Epoch 939/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0040 - mean_squared_error: 0.0040
Epoch 940/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0039 - mean_squared_error: 0.0039
Epoch 941/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0038 - mean_squared_error: 0.0038
Epoch 942/1000
63/63 [==============================] - 0s 978us/step - loss: 0.0039 - mean_squared_error: 0.0039
Epoch 943/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0040 - mean_squared_error: 0.0040
Epoch 944/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0037 - mean_squared_error: 0.0037
Epoch 945/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0046 - mean_squared_error: 0.0046
Epoch 946/1000
63/63 [==============================] - 0s 1ms/step - loss: 0.0037 - mean_squared_error: 0.0037
Epoch 947/1000
63/63 [==============================] - 0s 981us/step - loss: 0.0039 - mean_squared_er

In [9]:
ann.predict([30*np.pi/180])

array([[0.47796795]], dtype=float32)

In [10]:
ann.predict([-30*np.pi/180])

array([[-0.5210119]], dtype=float32)

In [11]:
ann.predict([45*np.pi/180])

array([[0.68725127]], dtype=float32)

In [12]:
ann.predict([-45*np.pi/180])

array([[-0.7328345]], dtype=float32)

In [13]:
ann.predict([90*np.pi/180])

array([[1.005175]], dtype=float32)

In [14]:
ann.predict([-90*np.pi/180])

array([[-0.9568225]], dtype=float32)

In [15]:
ann.predict([4*np.pi])

array([[3.0241382]], dtype=float32)

In [16]:
ann.predict([0])

array([[0.03011378]], dtype=float32)

In [17]:
ann.predict([2*np.pi])

array([[-0.12457535]], dtype=float32)

In [18]:
ann.predict([270*np.pi/180])

array([[-0.9618265]], dtype=float32)

In [19]:
ann.predict([-270*np.pi/180])

array([[0.9065718]], dtype=float32)

In [22]:
tf.keras.utils.plot_model(ann,show_shapes = True)

('You must install pydot (`pip install pydot`) and install graphviz (see instructions at https://graphviz.gitlab.io/download/) ', 'for plot_model/model_to_dot to work.')


In [25]:
winget install graphviz

SyntaxError: invalid syntax (<ipython-input-25-cc0bff49b42f>, line 1)

In [ ]:
ann.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense (Dense)                (None, 40)                80        
_________________________________________________________________
dense_1 (Dense)              (None, 12)                492       
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 13        
Total params: 585
Trainable params: 585
Non-trainable params: 0
_________________________________________________________________


In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import pandas as pd
pd.read_csv('/content/drive/MyDrive/Churn_Modelling.csv')

RowNumber  CustomerId    Surname  ...  IsActiveMember EstimatedSalary Exited
0             1    15634602   Hargrave  ...               1       101348.88      1
1             2    15647311       Hill  ...               1       112542.58      0
2             3    15619304       Onio  ...               0       113931.57      1
3             4    15701354       Boni  ...               0        93826.63      0
4             5    15737888   Mitchell  ...               1        79084.10      0
...         ...         ...        ...  ...             ...             ...    ...
9995       9996    15606229   Obijiaku  ...               0        96270.64      0
9996       9997    15569892  Johnstone  ...               1       101699.77      0
9997       9998    15584532        Liu  ...               1        42085.58      1
9998       9999    15682355  Sabbatini  ...               0        92888.52      1
9999      10000    15628319     Walker  ...               0        38190.78      0

[10000 rows x 14 columns]

In [ ]:
y_pred = ann.predict(x)

In [ ]:
np.mean(np.square(y_pred-y))

0.00013447920172803855